spring:
  application:
    name: initial-project
  datasource:
    url: jdbc:mysql://localhost/initial-project?useSSL=false&useUnicode=yes&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    locations: classpath:db/migration